### ISSUE TITLE
v1.4 undefined reference to 'dotconf_continue_line_new' in src/dotconf.c

### ISSUE THREAD

**Issue by brechtsanders** [williamh/dotconf#7]
Building version 1.4 failed on src/dotconf.c with the error: `undefined reference to 'dotconf_continue_line_new'`

Replacing `dotconf_continue_line_new` with `dotconf_continue_line` allows the build to continue, but I'm not sure this is okay to do.

**Comment by addisoncrump** [comment]
Fixed by #8

**Comment by addisoncrump** [comment]
I would leave this open until merged, just in case others come along with the same question :slightly_smiling_face:
